### ISSUE TITLE
Add semantic tags [Proposal]

### ISSUE THREAD

**Issue by PeterMitrano** [GrinningHermit/Cozmo-Animation-Explorer#2]
It would be awesome to tag the animations for faster searching. For instance, I would tag `anim_meetcozmo_lookface_getout` as "ding" because that's how I remember it. I don't have a proposal on how to implement this, mostly because I haven't read your code yet, but it popped into my mind so I thought I'd mention it. I don't think it needs to be any more complex than a static set of strings for each animation, and we can hardcode some tags and let people pull-request/open issues to add ones they feel are helpful in finding the right animation.

more example tags: happy, sad, giggle, sneeze, dance, tantrum, afraid

**Comment by GrinningHermit** [comment]
Sorry for the late reply, I forgot to set watching for this repository :( Adding tags would be a great idea. Although I'd like it to be a connected online database to request and update the tags with. Probably overkill for the intended purpose, but something I'd enjoy researching once I'm more familiar with server-side programming. Short term solution and MVP would be your suggestion.

**Comment by PeterMitrano** [comment]
working on a PR for this. God I hate javascript...

**Comment by GrinningHermit** [comment]
It might be an idea to work out something on paper or digitally. That way we can iterate before investing a lot of time in coding. Plus, I've been asked to add triggers and behaviors. For the latter I already worked something out in design that I can share. Can we use that as a starting point on how to implement tagging?

**Comment by GrinningHermit** [comment]
Development has moved to https://github.com/GrinningHermit/Cozmo-Explorer-Tool. If the requested feature is built, it will be a part of that repository.
